version: '3'

services:

  database:
    image: postgres:16.1-bullseye
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data      

  principal:
    build:
      context: ./principal
    ports:
      - "8000:8000"  
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@database:5432/mydatabase
    volumes:
      - ./principal:/app      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080

volumes:
  postgres_data: